#server:
#  servlet:
#    context-path: /api

# context-path 때문에 thymeleaf 가 작동을 안하는 거였음

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/googleauth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: phj@3473

  main:
    allow-bean-definition-overriding: true
